[tool.ruff]
line-length = 88
show-fixes = true

[tool.ruff.lint]
select = [
    "F",  # Pyflakes
    "E",  # Pycodestyle
    "W",  # Pycodestyle
    "UP",  # pyupgrade
    "I",  # isort
    "PL", # Pylint
    "T201", # Print Statement
]
ignore = ["E501"]  # Black take care off line-too-long
unfixable = []

[tool.ruff.lint.per-file-ignores]
"{tests,docs}/*" = ["T201"]  # Check print statement for kedro/ only
